### ISSUE TITLE
Could not get it to work for non-local environment

### ISSUE THREAD

**Issue by jafar-albadarneh** [laravel/telescope#76]
At first, i'd like to appreciate your efforts in producing such an amazing package.
I've updated the `Gate::define` method to return always true

Nothing is being logged to telescope. telescope entries table is empty, although I made sure the all flags in `config/telescope` is set to true.
Any clue where the problem could be ?

**Comment by L3o-pold** [comment]
Remove this from the register function

`
Telescope::filter(function (IncomingEntry $entry) {
            return true;
            if ($this->app->environment() == 'local') {
                return true;
            }

            return $entry->isReportableException() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
});
`

**Comment by jafar-albadarneh** [comment]
@L3o-pold Perfect, Thanks

**Comment by 120dev** [comment]
excuse me i can not run out of the local `env`

```
  public function register()
    {
        // Telescope::night();

        Telescope::filter(function (IncomingEntry $entry) {
           return true;

            return $entry->isReportableException() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }

    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return true;
        });
    }
```

**Comment by L3o-pold** [comment]
@120dev It should works, what kind of message do you have?

**Comment by dramen** [comment]
+1, can't connect the dashboard with production env.

**Comment by mydnic** [comment]
+1 I got 403 Forbidden in Production even if the Gate returns always true

**Comment by andreshg112** [comment]
Same here! It works when I use `APP_ENV=local`.

I tried @dramen solution but It didn't worked for me.

app.php
```php
'providers' => [

        /*
     * Laravel Framework Service Providers...
     */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\TelescopeServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        // Agregados por mí.
        crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,
        App\Providers\TelescopeServiceProvider::class,
    ],
```

TelescopeServiceProvider.php
```php
protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return true;
            // return \CRUDBooster::isSuperadmin();
        });
    }
```

![image](https://user-images.githubusercontent.com/15859884/47942570-65ee4000-dec0-11e8-949f-ce0b0455209d.png)

**Comment by andreshg112** [comment]
I just updated to Telescope 1.0 and the problem is still the same.
```php
Gate::define('viewTelescope', function ($user) {
            return true;
            // return \CRUDBooster::isSuperadmin();
        });
```

**Comment by paras-malhotra** [comment]
Guys, we'd love to help but we aren't able to reproduce this. 

So, here are some guidelines/checks:
1. Do you see any error logs (backend logs or console frontend errors)?
2. Do you have a `Telescope::filter` or `Telescope::filterBatch` call in your `App\Providers\TelescopeServiceProvider`? If yes, does it satisfy the filter condition? The default `TelescopeServiceProvider` stub allows all entries to be recorded in local environments but for production only allows reportable exceptions, failed jobs, scheduled tasks and monitored tag entries to be recorded.
3. Did your `authorization` pass through? The default `authorization` method in the `TelescopeServiceProvider` stub always passes for local environments but does the gate check for production.
4. Do you have auto discovery enabled in production? If not, did you add the `Laravel\Telescope\TelescopeServiceProvider` in your `config/app.php`?
5. Did you add your `App\Providers\TelescopeServiceProvider` to your `config/app.php`?
6. Is telescope enabled in production? Check the env variable `TELESCOPE_ENABLED` if set. Defaults to true if not set.

If all of these are okay but you're still facing issues, please share a Github repo with this reproducible issue.

**Comment by Braunson** [comment]
@paras-malhotra 

1. No errors
2. Yes see below, but it's the same as the docs, also it records everything properly on local but not on production/development environment.
3. Yes I can see Telescope on all environments properly
4. Yes
5. Yes

```
<?php

namespace App\Providers;

use Laravel\Spark\Spark;
use Laravel\Telescope\EntryType;
use Laravel\Telescope\Telescope;
use Illuminate\Support\Facades\Gate;
use Laravel\Telescope\IncomingEntry;
use Laravel\Telescope\Contracts\EntriesRepository;
use Laravel\Telescope\TelescopeApplicationServiceProvider;

class TelescopeServiceProvider extends TelescopeApplicationServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        Telescope::night();

        Telescope::filter(function (IncomingEntry $entry) {
            // Are we local?
            if ($this->app->environment() == 'local') {
                return true;
            }

            return $entry->isReportableException() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }

    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return Spark::developer($user->email);
        });
    }
}
```

**Comment by Braunson** [comment]
@paras-malhotra Ah ok, It was weird because this previous to v0.1.8/1.0 everything recorded regardless of environment. Must have been a code change

**Comment by andreshg112** [comment]
@paras-malhotra 

1. I can't see any error in the logs. In addition, I use Sentry and no error is reported.
![image](https://user-images.githubusercontent.com/15859884/48580686-e0ba5080-e8ed-11e8-9731-2cc16a69f525.png)

2. Telescope is recording events even in production.
![image](https://user-images.githubusercontent.com/15859884/48577999-8ff32980-e8e6-11e8-8295-aed30f1ffb1d.png)

3. Which `authorization` method? This is my code:
```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Laravel\Telescope\IncomingEntry;
use Laravel\Telescope\Telescope;
use Laravel\Telescope\TelescopeApplicationServiceProvider;

class TelescopeServiceProvider extends TelescopeApplicationServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        // Telescope::night();

        Telescope::filter(function (IncomingEntry $entry) {
            if ($this->app->environment('local')) {
                return true;
            }

            return $entry->isReportableException() ||
                $entry->isFailedJob() ||
                $entry->isScheduledTask() ||
                $entry->hasMonitoredTag();
        });
    }

    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return true;
            // return \CRUDBooster::isSuperadmin();
        });
    }
}

```

4. I haved added to app.php. Look at the comment above https://github.com/laravel/telescope/issues/76#issuecomment-435521446

5. If I don't have to manually add packages to app.php, so I think It's enabled. However, I manually added to it.
```php
'providers' => [

        /*
     * Laravel Framework Service Providers...
     */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\TelescopeServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        // Agregados por mí.
        crocodicstudio\crudbooster\CRUDBoosterServiceProvider::class,
        \Laravel\Telescope\TelescopeServiceProvider::class,
        App\Providers\TelescopeServiceProvider::class,
    ],
```

6. Yes, It is.
![image](https://user-images.githubusercontent.com/15859884/48581481-f2045c80-e8ef-11e8-99a1-8a0c066b68c4.png)

**Comment by andreshg112** [comment]
If I change APP_ENV to local in the server, It shows the dashboard.

**Comment by EdwinDayot** [comment]
Changed the Authorize middleware by my own as following:
```
class Authorize
{

    /**
     * @param $request
     * @param $next
     * @return mixed
     */
    public function handle($request, $next)
    {
        return $next($request);
    }
}
```

It fixed the 403 Forbidden on a production server.
Used with the removal of the Telescope::filter, it fixed the whole thing for me.

**Comment by sijones-uk** [comment]
If you've been following the instructions in the section ["Installing Only In Specific Environments"](https://laravel.com/docs/5.7/telescope#installation) you'll need to ensure that you update your `AppServiceProvider` accordingly, e.g.

```
public function register()
{
	if ($this->app->environment('local') || $this->app->environment('staging')) {
		$this->app->register(TelescopeServiceProvider::class);
	}
}
```

**Comment by andreshg112** [comment]
I'm trying this and I'm still getting 403.
```php
public function register()
    {
        $this->app->register(TelescopeServiceProvider::class);
    }
```

![image](https://user-images.githubusercontent.com/15859884/49093202-9ad88300-f231-11e8-8432-b566d7673ebd.png)

**Comment by rikiless** [comment]
Is it possible to remove selected incoming entries from `Telescope::filter()` as used in default file of TelescopeServiceProvider?

```php
return $entry->isReportableException() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();

// Allow more entries here. For example: Redis, Mail, Events...
```

thanks

**Comment by biniyam17** [comment]
Hi, is there a reason why Telescope does not register any of my browser actions? Dump, requests, sql queries, etc... do not show up on my telescope application.

**Comment by glendmaatita** [comment]
in my side, i found the problem was on its Authorization mechanism. so, we can replace it with our own auth mechanisme. now, mine is:

in `config/telescope.php`
```
    'middleware' => [
        'web',
        // Authorize::class,
        'admin'
    ],
```

**Comment by robertmylne** [comment]
Won't work for me in production no matter what:

```
    'middleware' => [
        'web',
//        Authorize::class,
    ],
```
```
    public function register()
    {
        // Telescope::night();

        $this->hideSensitiveRequestDetails();

//        Telescope::filter(function (IncomingEntry $entry) {
//            if ($this->app->isLocal()) {
//                return true;
//            }
//
//            return $entry->isReportableException() ||
//                   $entry->isFailedJob() ||
//                   $entry->isScheduledTask() ||
//                   $entry->hasMonitoredTag();
//        });
    }
```
```
        Gate::define('viewTelescope', function ($user) {
            return true;
//            return in_array($user->email, [
//                ''
//            ]);
        });
```
```
APP_ENV=local
```

In production always gives me 403, thought the database entries are all being created.

**Comment by squatto** [comment]
The problem appears to be the following method in `TelescopeApplicationServiceProvider`:

```php
    /**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return app()->environment('local') ||
                   Gate::check('viewTelescope', [$request->user()]);
        });
    }
```

I overrode this method in my `TelescopeServiceProvider` and defined my own auth closure:

```php
    /**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return $this->app->environment(['local', 'staging']) ||
                   Gate::check('viewTelescope', [$request->user()]);
        });
    }
```

This allowed me to access telescope in my staging environment. I tried changing my `gate()` override and it didn't appear to work. This was the only way that I could reliably get it to work.

**Comment by Punksolid** [comment]
As @glendmaatita says I did a middleware exclusively for telescope
// telescope.php
```php
    'middleware' => [
        'web',
        TelescopeMiddleware::class,
        // Authorize::class,
    ],
```
php artisan make:middleware TelescopeMiddleware
```php
class TelescopeMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        
        if(auth()->check() && auth()->user()->email == "punksolid@gmail.com"){

            return $next($request);
        }
        abort(403);
    }
}

```

**Comment by neanderthil** [comment]
Literally tried everything in this thread and nothing worked other than modifying TelescopeServiceProvider closure. The Gate:: facade call ALWAYS returned false no matter the logic defined in the Provider. I ended up removing it entirely and adding in my own function call for IP whitelisting. Works!

```
protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return app()->environment('local') || Helper::isAllowedIp($request->ip());
        });
    }
```

**Comment by Ciaro** [comment]
No need to do some hackish things in the vendor files. There's a method on the Telescope facade which let you override the auth method of the shipped authorizer.

Put this somewhere in your _AppServiceProvider::boot_ method:

```
Telescope::auth(function () {
   // Your custom boolean check
   return true; // = public access
});
```

**Comment by hmshafeeq** [comment]
Changed telescope authorization middleware with laravel's authentication middleware as a workaround. 

`'middleware' => [
        'web',
       // Authorize::class,
        \App\Http\Middleware\Authenticate::class,
 ],`

**Comment by ElderCastroLima** [comment]
> in my side, i found the problem was on its Authorization mechanism. so, we can replace it with our own auth mechanisme. now, mine is:
> 
> in `config/telescope.php`
> 
> ```
>     'middleware' => [
>         'web',
>         // Authorize::class,
>         'admin'
>     ],
> ```

Thanks, i just comment 'Authorize::class'

**Comment by RuanHerculano** [comment]
None of the above answers solved my problem.
![Screenshot from 2019-08-20 16-50-13](https://user-images.githubusercontent.com/9044734/63379760-59fa3e80-c36b-11e9-9764-fb3c04706c8f.png)

**Comment by gl3nda85** [comment]
@RuanHerculano that error is caused because your assets are not being served over https we use this in production 
`if (App::environment('production')) {
            // The environment is production
            URL::forceScheme('https');}
`

**Comment by hwbrzzl** [comment]
Telescope`s gate can run right when `Auth::user()` had value. So,if you didn't login,you could not view telescope in production.

**Comment by mohitpawar10** [comment]
This issue is due to an empty or non logged user. Laravel gate receives user as the first argument if it's empty it doesn't care about internal code. If you want to use it without gate just remove gate function from TelescopeServiceProvider class and override authorization function. See the example below. 

 /**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return app()->environment('local') ||
                   **in_array($request->ip(), config('allowed_ip_addresses.telescope'))**;
        });
    }

I removed the gate define as well as gate check, so issue is resolved.

**Comment by Ovab** [comment]
In config/telescope.php you can configure your own authentication with a middleware if you want to build your own thing (if your company has it's own CMS for example) or just want to only let through whitelisted ip's

**Comment by drobinetm** [comment]
Hello Team

With these steps you resolve the issue:

1. Create a middleware class that inherits from Authenticate and in the handler function write:

` public function handle($request, Closure $next, ...$guards): mixed
  {
        if (app()->environment('local')) {
            return $next($request);
        }

        if (app()->environment('production') && !$request->expectsJson()) {
           parent::handle($request, $next, ...$guards);
        }

        return abort(403);
  }
`
2. Add the middleware class in the config/telescope.php

`   'middleware' => [
        'web',
        AuthorizeTelescope::class,
    ],
`

**Comment by MladenJanjetovic** [comment]
Fresh install of latest Laravel and Telescope and this is still not working on non-local environments.
Latest documentation followed and nothing was customized.

Simple returning the TRUE is not working in the `TelescopeServiceProvider` gate method:

```
 protected function gate(): void
    {
        Gate::define('viewTelescope', function ($user) {
            return true;
        });
    }
```

**Comment by xDaemonic** [comment]
I can solve it by rewrite authorization method

/**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            if ($request->get('_token')) {
                $user = PersonalAccessToken::findToken($request->get('_token'))->tokenable;
                return $user->name === 'admin';
            }

            return Gate::check('viewTelescope', [$request]);
        });
    }

**Comment by kingeke** [comment]
My issue was mostly that I wasn't logged in, when i logged in I could then access the user param and that worked as expected.

**Comment by saschaglo** [comment]
Hi guys, to all of you who are coming across this problem - I have been struggling with this for hours now and finally found the "solution" (aka easier fix to this instead of creating a whole new middleware etc.).

The reason for this "issue" that we all had is because Laravel has some internal check whether this callback is supported for also work with guest-visitors (aka non-logged-in users). The default is (since it comes with the provider from telescope) that it **does not** these guest users!

To make it work, you need to change the code from

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user) {
        return in_array($user->email, [
            //
        ]);
    });
}
```

to this:

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user = null) {
        return in_array($user->email, [
            //
        ]);
    });
}
```

The only change is that you've to add the default value `null` here to the parameter in the callback-function. With this you change the evaluation for whether this gate is suitable to be taken into account or not. The check is part of the `Auth` modules and the method that does this magic is `canBeCalledWithUser`, if you need further insides.

The only thing you have to aware of is that the user object then is always null but you can still do things like:

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user = null) {
        return in_array(request()->ip(), ['123.123.123.123', ...]);
    });
}
```

**Comment by saschaglo** [comment]
Hi guys, to all of you who come across this problem - I have been struggling with this for hours now and finally found the "solution" (aka easier fix to this instead of creating a whole new middleware etc.).

The reason for this "issue" that we all had is because Laravel has some internal check whether this callback is supported for also work with guest-visitors (aka non-logged-in users). The default is (since it comes with the provider from telescope) that it **does not** these guest users!

To make it work, you need to change the code from

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user) {
        return in_array($user->email, [
            //
        ]);
    });
}
```

to this:

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user = null) {
        return in_array($user->email, [
            //
        ]);
    });
}
```

The only change is that you've to add the default value `null` here to the parameter in the callback-function. With this you change the evaluation for whether this gate is suitable to be taken into account or not. The check is part of the `Auth` modules and the method that does this magic is `canBeCalledWithUser`, if you need further insides.

The only thing you have to aware of is that the user object then is always null but you can still do things like:

```php
protected function gate(): void
{
    Gate::define('viewTelescope', function ($user = null) {
        return in_array(request()->ip(), ['123.123.123.123', ...]);
    });
}
```

**Comment by trioangle27** [comment]
laravel telescope is not working in my domain ip address.but all configuration is correctly.why ? i am using domain ip .
like example :http://44.193.10.70/telescope

**Comment by sergannn** [comment]
i have made this 
my logged user have this email, it works now - or you can just make return true;
 protected function gate(): void
    {
        
        Gate::define('viewTelescope', function ($user=null) {
      //      echo $user;
            return in_array($user->email, [ 'doctor@infycare.com'
                //
            ]);
        });
